stages:
  - build
  - dockerize

variables:
  GO_VERSION: "1.24.2"
  DOCKER_IMAGE_VERSIONED: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  DOCKER_IMAGE_LATEST: "$CI_REGISTRY_IMAGE:latest"

build:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - echo "Building Go binary..."
    - go mod download
    - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o myapp main.go
  artifacts:
    paths:
      - myapp
  rules:
    - if: $CI_COMMIT_TAG
dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  needs:
  - job: build
    artifacts: true
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - echo "Copying binary into Docker image..."
    - docker build -t "$DOCKER_IMAGE_VERSIONED" -t "$DOCKER_IMAGE_LATEST" .
    - docker push "$DOCKER_IMAGE_VERSIONED"
    - docker push "$DOCKER_IMAGE_LATEST"
  rules:
    - if: $CI_COMMIT_TAG